name: Create Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build image
        run: |
          pwd
          ls -la
          docker build -t test src/

